### ISSUE TITLE
Error on upload screen

### ISSUE THREAD

**Issue by hujiba** [7x11x13/songs-to-youtube#10]
I'm getting this error when uploading a song:
`selenium.common.exceptions.InvalidArgumentException: Message: File not found: F:\...\song.flac.mkv`
This is the screenshot it provides:
![2021-07-01_123559](https://user-images.githubusercontent.com/34780215/124180579-3d4fe700-da69-11eb-8797-2773e7c31775.png)
It won't get past this point

**Comment by 7x11x13** [comment]
1. If you render without uploading to youtube, is the video file created in the expected place?
2. Does it only happen with this one song?
3. What's the actual file path?

**Comment by hujiba** [comment]
1. Yes
2. No
3. F:\owcsc\Husk Recordings\Music\Katamari Democracy\The Essential\audio\02 Psycho Girls.flac.mkv

**Comment by 7x11x13** [comment]
Do you notice a pattern between songs that work and songs that don't? Maybe try changing the output directory... I'm unable to reproduce :/
