### ISSUE TITLE
Add possibility to exclude certain extensions

### ISSUE THREAD

**Issue by Sakimotor** [7x11x13/songs-to-youtube#11]
My program just failed a render because of an .m3u file within the album folder xd

![image](https://user-images.githubusercontent.com/20578016/125625254-4dc9a8eb-6414-4b5e-a48c-4dbda9906658.png)

**Comment by 7x11x13** [comment]
Fixed in v0.10.2

Ignore files with mimetype `audio/x-mpegurl`
