### ISSUE TITLE
Invalid PNG signature when uploading tracks as one album to YouTube

### ISSUE THREAD

**Issue by xoark** [7x11x13/songs-to-youtube#14]
<img width="707" alt="Screenshot 2021-08-21 131551" src="https://user-images.githubusercontent.com/88959307/130331326-fcca04c6-d0c1-44dd-9670-f323572aef74.png">
Files seem to render but not upload to YouTube, not sure what is causing this

**Comment by xoark** [comment]
[](https://stackoverflow.com/questions/62404539/invalid-png-signature-0xffd8ffe000104a46-error-while-decoding-stream-00-inva)
I found this, it may be an ffmpeg thing

**Comment by xoark** [comment]
https://stackoverflow.com/questions/62404539/invalid-png-signature-0xffd8ffe000104a46-error-while-decoding-stream-00-inva

**Comment by 7x11x13** [comment]
That album renders fine for me, with both cover file and embedded cover art. Are you using a different image? What version of ffmpeg are you using?

**Comment by xoark** [comment]
I'm using ffmpeg 4.4, and with embedded images from the discogs release of the above album via mp3tag + the original image I created as the cover.
