### ISSUE TITLE
Error when uploading / .exe version v0.11.15

### ISSUE THREAD

**Issue by Dezperados** [7x11x13/songs-to-youtube#18]
First of all, thanks for making this amazing tool. It works exactly how I want it to work. Sadly, I do come across a error when the tool comes on the monetization page. From how I can read the screenshot and the logs, turning on the monetization on a video isn't programmed and for that reason, the tool can't go further than that page.

Luckily the video comes through perfectly on YouTube, so it functions. It's just a bummer that it will always show "[SUCCESS] 0/1 uploads successful" now unless I will shut down the tool and fill in the last parts by hand. For that reason, it will also not delete the video file locally so for now I have to do that by hand too.

The error log:
[ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 159, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 190, in upload
  File "youtube_uploader_selenium\__init__.py", line 472, in __upload
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="UNLISTED"]

Hopefully you can find a way to fix it! Thanks in advance!
![error](https://user-images.githubusercontent.com/93384771/139435614-7fdc6a92-8c7d-4515-9dfd-69c613ee49b3.png)

**Comment by 7x11x13** [comment]
I don't have access to an account with monetization enabled, but if you save the page HTML on that monetization settings screen and send it to me (you can delete any personal information, just don't change the structure of the document), I can fix it.

**Comment by Dezperados** [comment]
Sure! In this topic or to your email? Because I can't find it on your page.

**Comment by 7x11x13** [comment]
Yes, you can email me at x7x11x13@gmail.com

**Comment by Dezperados** [comment]
Sent!

**Comment by Dezperados** [comment]
Any updates?

**Comment by 7x11x13** [comment]
I've been very busy with other work recently and this isn't a priority for me since I don't have monetization enabled. When I have more free time I will get around to it, I promise.

**Comment by Dezperados** [comment]
Thank you!
