### ISSUE TITLE
When I render albums as a single video they are 66 hours long

### ISSUE THREAD

**Issue by binkelderg** [7x11x13/songs-to-youtube#20]
Problem above. 
Geckodriver and ffmpeg installed. 
Didn't have this problem before and it always happens now. It doesn't show any errors, either.

**Comment by 7x11x13** [comment]
What version of ffmpeg? Also, send me one of the albums

**Comment by binkelderg** [comment]
I just updated it yesterday because I thought it was outdated, to no avail. Still doesn't work so I doubt it's an ffmpeg problem, especially because it still worked a few weeks ago. 

I tried it with this one: http://subkultur-ost.de/V.A.%20Rubbeln%20&%20Schnuppern%20Weltfremd%20Kassette%207%20%6082.rar

**Comment by binkelderg** [comment]
Okay, I've found that the problem lies with those specific files, as it works perfectly fine with music from other sites like Spotify, Bandcamp and Soundcloud, but why?

**Comment by binkelderg** [comment]
Okay, I've identified the problem: ffmpeg apparently doesn't really work with the FHG encoder. I had to convert the album via Foobar into LAME-encoded MP3 files and redo some of the metadata until it finally worked. Mehh.

**Comment by 7x11x13** [comment]
The album you sent works fine for me with ffmpeg version 4.4-72 with configuration `--enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp`
as well as ffmpeg version 5.0 with configuration `--enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint`

**Comment by qyZMVYcw1VA6** [comment]
just as a general rule of thumb to anyone else who stumbles across this, try converting your album to WAV and using the program again -- no need to fiddle with metadata etc as suggested above and there will be no risk of quality loss this way.
