### ISSUE TITLE
File naming serial number

### ISSUE THREAD

**Issue by mrmelwynm** [7x11x13/songs-to-youtube#21]
Hi, thanks for this wonderful tool. Just what i was looking for. Am not a coder so took me some time to figure out the entire process and get it to working perfectly. My only query now is how do i insert the name of the original mp3 file to show as the video title. I know there are tags and strings to do this that extract info from the metadata. I just simply want the exact mp3 file name to show up as video title on youtube. Would be of immense help if someone could guide me on this. Thanks in advance!

**Comment by 7x11x13** [comment]
~{song_file} should be the file name

**Comment by mrmelwynm** [comment]
> 
Thanks. Worked.
