### ISSUE TITLE
Unable to upload due to Youtube's "verify it's you" prompt

### ISSUE THREAD

**Issue by xoark** [7x11x13/songs-to-youtube#22]
<img width="862" alt="unknown (240) edit" src="https://user-images.githubusercontent.com/88959307/150274831-4c55090b-8d1f-4076-af17-fe2f8c820a5c.png">
![image](https://user-images.githubusercontent.com/88959307/150274851-2e3afc3b-03d8-4db3-9934-5ce250111b41.png)
These are preventing me from being able to upload music on an account...not sure how to get past this

**Comment by xoark** [comment]
![unknown (241)](https://user-images.githubusercontent.com/88959307/150274943-25a31535-65c4-451a-96f6-242f8236ae5b.png)

**Comment by xoark** [comment]
I have attempted to upload that same file that it generated manually (as a private upload) and that worked successfully...

**Comment by xoark** [comment]
<img width="324" alt="firefox_VH6NqsK1dQ" src="https://user-images.githubusercontent.com/88959307/150276821-9bf88e5a-e7b1-49e2-ad60-841db8f3aa0b.png">
Tried to go and press "proceed" on the prompt and got this message

**Comment by 7x11x13** [comment]
You could try signing out and signing back in and getting the cookies again, or maybe changing IP address (if you're using a VPN turn it off). On my end I could migrate to using a more stealthy automated browser but who knows if it would even work for sure.

**Comment by xoark** [comment]
ok, turns out that enabling 2FA + getting cookies again + not using incognito mode seems to fix the issue for me
