### ISSUE TITLE
my google account got disabled or something.. cant login, please help!

### ISSUE THREAD

**Issue by nitrotech7** [7x11x13/songs-to-youtube#23]
Hi, I just tried ur app and as it was processing a song my google account got signed out and i cannot sign back in again!! its like it was hacked or something i dont get it!? freaking out

it keeps always telling me: "Google couldn’t verify this account belongs to you."

and 

"A suspicious application may have accessed your account

Someone may have accessed your account using a suspicious application installed on your device. To keep your account secure, we've logged you out of it."

I tried everything to recover my account but nothing is working, not even on my phone. i got signed out everywhere! can u please tell what the hell is going on as this is ur app?? I had a bad feeling about providing my cookie json file, now look what happened. i should have used at least a burner account..smh

here is the output log from ur app: https://pastebin.com/j6aPHZJh

id just like my account back, and ill stay far away from ur app in the future...

**Comment by 7x11x13** [comment]
What did you try exactly? Clearing cookies/signing in on incognito tab, resetting password maybe?

**Comment by nitrotech7** [comment]
> What did you try exactly? Clearing cookies/signing in on incognito tab, resetting password maybe?

Everything. I tried to sign in via incognito tab, it keeps saying 
Couldn’t sign you in
You’ve tried to sign in too many times. For your protection, you can’t sign in right now.
Try again later or sign in from a different device.

This happens both on my mobile phone and PC.

If i click "Forgot password" it says enter ur previous password u remember. I do it and then it says "Google couldn’t verify this account belongs to you."
Im stuck in this "loop" for the last 2 hours.. I already contacted google but seems like i got a robots reply instead of some human:

Hello Google user,
Thank you for contacting us about being unable to access your Google account. We've looked into your account and confirmed that it is still active, so you should be able to log in normally.
Please try logging again. If you can’t remember your password use this (https://www.google.com/accounts/recovery/) form (https://www.google.com/accounts/recovery/) and select “I don’t know my password”. If you can't remember your username, but still have access to the email address you used to create your account, you can regain access to your account by selecting "I don't know my username."
If you are having other problems signing in, please go to this (http://support.google.com/accounts/bin/static.py?hl=en&ts=2402620&page=ts.cs) form (http://support.google.com/accounts/bin/static.py?hl=en&ts=2402620&page=ts.cs) to troubleshoot your issue.
Best,
The Google Accounts Team


I dont know what else to do besides wait?? tmrw, few days, a week? will things change. i somehow doubt it but like this is bs. and who;s going to help me recover my account when google has robots as service men ffs..

please if u have any suggestions or idea as to what i can do, how this happened, wutever, it wud help alot. its my main secondary email account and pretty important especially for youtube and gmail.

**Comment by 7x11x13** [comment]
I think just waiting and trying again later, or signing in from a different IP address (maybe try a vpn or mobile hotspot)

**Comment by nitrotech7** [comment]
> I think just waiting and trying again later, or signing in from a different IP address (maybe try a vpn or mobile hotspot)

omg.. thanks so much for suggesting to try a diff IP address aka using my mobile network instead of my home wifi.. i should have thot of this but its late like 3.30am...

i recovered my account, was able to reset my password using my recovery email account thats linked to it, an old yahoo account which i nearly forgot the pass to as well lol

back to the issue at hand tho, how the hell did this happen? do u know what went wrong? im sure i wont be the last person who tries ur app and suffers the same consequences.. i mean this was a big lesson for me: ALWAYS USE EMPTY JUNK BURNER ACCOUNTS! LOL
but even if i do, ur app still didnt upload the song/video... how can i get that to work? did u see the errors in the pastebin link i provided? looks like some python stuff, im not too familiar with python. am i missing some other software besides ffmpeg and geckodriver?

thanks

**Comment by tommy-mor** [comment]
I don't know specifically but you're not the only one with gmail security problems: https://news.ycombinator.com/item?id=30051054
