### ISSUE TITLE
No cookie files matching *youtube*.pkl or *youtube*.json found

### ISSUE THREAD

**Issue by thompcha** [7x11x13/songs-to-youtube#35]
I'm using the [v0.11.22](https://github.com/7x11x13/songs-to-youtube/releases/tag/v0.11.22) binary on a mac.

> [10:04:58] [ERROR] Traceback (most recent call last):
>   File "upload.py", line 29, in run
>   File "youtube_uploader_selenium/__init__.py", line 70, in __init__
> FileNotFoundError: No cookie files matching *youtube*.pkl or *youtube*.json found in /Users/[user]/Library/Application Support/7x11x13/songs-to-youtube/cookies/[youtube user]

It appears I need to locate a cookie file someplace in my filesystem. Can you please provide guidance in how to do this?

**Comment by DrearyWillow** [comment]
I'm not sure if this is a mac directories issue or a cookies issue (I don't use a mac), but if it's the latter have you tried doing the standard cookies procedure?

1. get a browser extension like [this one](https://github.com/ktty1220/export-cookie-for-puppeteer)
2. login to youtube
3. **while on the youtube page**, use the extension to get the cookies file
4. in songs-to-youtube, go to file > settings > upload videos as: > add new user
5. enter a username and locate to the cookies file
6. click ok and upload videos
