### ISSUE TITLE
geckodriver - Machine Type Mismatch/uploading error? (Win10 Home 64-bit)

### ISSUE THREAD

**Issue by LifeLineRH** [7x11x13/songs-to-youtube#36]
I read the instructions carefully. I already have Firefox (108.0.1, 64-bit, as of this writing), since it's my browser of choice. I made sure, following [this guide](https://www.java.com/en/download/help/path.html), that the PATH environment variable had the folder paths to both geckodriver _and_ ffmpeg (the latter specifically from [this Windows build directory](https://github.com/BtbN/FFmpeg-Builds/releases)). I copied the cookies for my YouTube login and account and added it through the user settings of the program.

While converting into a video seems to... _somewhat_ work (I'm personally getting this corrupt "green" video stream effect for the output whenever it renders, whether in mkv or mp4; it might be an issue with both ffmpeg _and_ the PC/laptop I have), but anytime it goes into the actual "upload to YouTube" part of the process, I get these errors:

>  [17:59:19] [ERROR] Traceback (most recent call last):
>   File "upload.py", line 29, in run
>   File "youtube_uploader_selenium\__init__.py", line 79, in __init__
>   File "selenium\webdriver\firefox\webdriver.py", line 164, in __init__
>   File "selenium\webdriver\common\service.py", line 72, in start
>   File "subprocess.py", line 858, in __init__
>   File "subprocess.py", line 1311, in _execute_child
> OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

I then tried experimenting by removing the paths to the separate geckodriver and ffmpeg folders from the PATH environment variable, and copying/putting the required files for them directly in the folder where the songs-to-youtube executable is. It seemed to work just fine/the same with that method; then on the same "upload to YouTube" part, right before getting the same logged error, I get this _additional_ Windows error:

![image](https://user-images.githubusercontent.com/67207428/210179676-c44ee708-b3d7-45f7-b528-6ad61e65aa06.png)

> **songs-to-youtube.exe - Machine Type Mismatch**
> The image file C:\songstoyoutube\geckodriver.exe is valid, but is for a machine type other than the current machine.

So it's something wrong with geckodriver, but I don't know _what_. I specifically downloaded geckodriver v0.32.0, for Windows and labeled "aarch64", since I have a 64-bit laptop (I've heard there's no differences between "x64", "AMD64" and "AARCH64", but...). I'm using using a 64-bit version of Windows 10 Home (yes, _Home_, **not** Pro), if it makes any difference.

**Comment by 7x11x13** [comment]
Your computer probably doesn't have an ARM processor, download the win32 build of geckodriver instead.

**Comment by LifeLineRH** [comment]
> Your computer probably doesn't have an ARM processor, download the win32 build of geckodriver instead.

Alright, I'll try the 32-bit version. It's so goddamn confusing since I usually go for the 64-bit versions of programs whenever possible, since, y'know, _I have a **64-bit computer?**_ But whatever.

**Comment by LifeLineRH** [comment]
Okay, just tried the 32-bit version of geckodriver. It seemed to work better right off the bat, since it opened as a CMD window; but then...

> [19:07:45] [ERROR] Traceback (most recent call last):
>   File "upload.py", line 29, in run
>   File "youtube_uploader_selenium\__init__.py", line 79, in __init__
>   File "selenium\webdriver\firefox\webdriver.py", line 170, in __init__
>   File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
>   File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
>   File "selenium\webdriver\remote\webdriver.py", line 321, in execute
>   File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

I'm not sure what the problem could be _now..._

**Comment by 7x11x13** [comment]
Do you have Firefox installed?

**Comment by LifeLineRH** [comment]
> Do you have Firefox installed?

I literally wrote in the initial post:

>I already have Firefox (108.0.1, 64-bit, as of this writing), since it's my browser of choice.
