### ISSUE TITLE
Some uploads become several hours long upon uploading to YouTube

### ISSUE THREAD

**Issue by dinkster** [7x11x13/songs-to-youtube#45]
Something about how the way some uploads are encoded has resulted in some super long upload lengths. The time on the thumbnail is correct but the videos themselves end up 12 hours long with most of it just being silence. A lot of the time these uploads just don't finish processing at all, but when they do they end up like these:
https://www.youtube.com/watch?v=3608AwoDAGs
https://www.youtube.com/watch?v=biSCMolu2bM

This only seems to be a problem with MP3 files, particularly ones downloaded from soundcloud (problem has been observed with both streamrips and direct downloads under the "more" button if the artist has enabled them). Just ran into a bunch and re-encoding them to .ogg with LameXP before sending them to this program fixes it. Low priority of course considering there's a workaround that only takes a few minutes but it would be nice if it was a simple fix.

**Comment by 7x11x13** [comment]
What version of FFmpeg are you using, and can you send me an example of one of the MP3 files? The version I tested the FFmpeg commands with is 4.4.1

**Comment by lc-guy** [comment]
Seeing this too, with ffmpeg 4.4.

https://files.catbox.moe/54ncmu.mp3
Example of such a file.

**Comment by 7x11x13** [comment]
Thanks for the example, I was able to reproduce and will look into it

**Comment by 7x11x13** [comment]
Seems like the file has an ID3 tag "length" which was overriding the Mutagen streaminfo tag called "length" since we store both in the Metadata.tags dict (which we probably shouldn't do but whatever). I've made the streaminfo tags override the ID3/other tags in case of a name collision (instead of the other way around) so this shouldn't be a problem anymore in v0.12.6
