### ISSUE TITLE
Code doesnt want to run

### ISSUE THREAD

**Issue by HevCuesta** [7x11x13/songs-to-youtube#5]
I've set everything up correctly, checked multiple times that everything is in order, downloaded and tried with multiple versions of both python and geckodriver. I even tried compiling the code myself but when I try running the .exe file this error comes up:
![image](https://user-images.githubusercontent.com/27823709/107553696-4ed94500-6bd5-11eb-8a1a-50b740ff58d4.png)

**Comment by 7x11x13** [comment]
If you run the exe from the command line, does it give a more descriptive error?

**Comment by HevCuesta** [comment]
Nope, and I probably should have added that running straight from source gives me this error message:

```
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\songs-to-youtube-0.4.1\main.py", line 111, in <module>
    shutil.copy(os.path.join(os.path.dirname(__file__), "presets", "default.ini"), get_settings().fileName())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/USER/AppData/Roaming/7x11x13/songs-to-youtube.ini'
```

**Comment by 7x11x13** [comment]
Thanks for testing, it should be fixed now

**Comment by HevCuesta** [comment]
Works perfectly now, btw when I tried logging in I had to change the language from Spanish to English in order for the script to work. 
Anyways, thanks!

**Comment by HevCuesta** [comment]
Oh yeah and I have a quick question, is there any way that I can make the cover art fit the whole video without changing the default resolution? (upscale the original cover art extracted from the metadata)

**Comment by 7x11x13** [comment]
Sure, just create a new ffmpeg command preset:
`ffmpeg -loglevel error -progress pipe:1 -y -r {inputFrameRate} -loop 1 -i "{coverArt}" -i "{song_path}" -r 30 -shortest -vf "scale={videoWidth}:{videoHeight}" -acodec libmp3lame -ab 320k -vcodec libx264 -fflags +shortest -max_interleave_delta 500M "{tempFileOutput}"`

This will fit the cover art to the output resolution, so it will be stretched out if it is a square. If you want to scale up the cover art to fit the output width and then crop the top and bottom, try this
`ffmpeg -loglevel error -progress pipe:1 -y -r {inputFrameRate} -loop 1 -i "{coverArt}" -i "{song_path}" -r 30 -shortest -vf "scale={videoWidth}:-2,crop={videoWidth}:{videoHeight}" -acodec libmp3lame -ab 320k -vcodec libx264 -fflags +shortest -max_interleave_delta 500M "{tempFileOutput}"`

Or you can set the output dimensions based on the cover art and not use any filters at all
`ffmpeg -loglevel error -progress pipe:1 -y -r {inputFrameRate} -loop 1 -i "{coverArt}" -i "{song_path}" -r 30 -shortest -acodec libmp3lame -ab 320k -vcodec libx264 -fflags +shortest -max_interleave_delta 500M "{tempFileOutput}"`

![Untitled](https://user-images.githubusercontent.com/32209764/107837883-0ce50600-6d71-11eb-87d7-b5fc142ea27d.png)
