### ISSUE TITLE
Album import broken in 0.12.x

### ISSUE THREAD

**Issue by absurdismworld** [7x11x13/songs-to-youtube#50]
Importing a folder or drag and dropping a folder for album uploads seems to be consistently broken in every version after 0.11.24

No error(s) is printed.

Versions 0.12, 0.12.5 and 0.12.10 tested on a clean Windows 11 install and they all seem to share the same issue. Same issue also occurs on Windows 10.

Gif of me reproducing the issue:

![fault](https://github.com/7x11x13/songs-to-youtube/assets/19274382/e71c5054-afd3-425e-b149-cb7b38b74783)

**Comment by 7x11x13** [comment]
I was able to reproduce using the PyInstaller executable but not with running from source, so it's probably something that happened when I updated to a newer PyInstaller version...

**Comment by absurdismworld** [comment]
Can confirm it's most likely a Pyinstaller issue, tried installing from PyPi and it works with no issues.

**Comment by 7x11x13** [comment]
Should be fixed with v0.12.11 (reverted to Python 3.10 for building with PyInstaller, seems to have worked)
