### ISSUE TITLE
Cookies expiring before videos being rendered

### ISSUE THREAD

**Issue by Blinkot** [7x11x13/songs-to-youtube#52]
I'm trying to upload a 10 songs album with 1 hour and 9 minutes of length into 2048*2048 videos with 6 ffmpeg workers. Whenever i try to upload videos, the rendering takes so long that the cookies expire by the time the videos are rendered. Is it normal for the cookies to expire this quickly or the encoding being this slow ? I get around 0.3x realtime when encoding in VP9 on my machine.

**Comment by 7x11x13** [comment]
What version of FFmpeg are you using?

**Comment by Blinkot** [comment]
i'm running version 6.1.1

**Comment by 7x11x13** [comment]
Can you try downgrading to version 4.4.1 and see if it works? I've had trouble with some of the latest versions.

**Comment by Blinkot** [comment]
i was running into some issues with axiom and anything higher than the version packaged with it too, I will try that tomorrow

**Comment by 7x11x13** [comment]
I've updated the rendering commands in v0.12.12 so they work with FFmpeg 6.1 Unfortunately they don't work with older versions of FFmpeg anymore but I've decided it's better to support new versions of FFmpeg

**Comment by Blinkot** [comment]
alright, didn't get to try the older versions yet, i'll let you know how it goes with newer ffmpeg versions

**Comment by Blinkot** [comment]
all good, not getting issues anymore, literally takes less than 15 secs to render compared to like 15 minutes before
