### ISSUE TITLE
Renders an empty mp4 with just the audio

### ISSUE THREAD

**Issue by iansquenet** [7x11x13/songs-to-youtube#56]
I'm able to see the actual cover thumbnail, but not when I open it in a video player.

![image](https://github.com/7x11x13/songs-to-youtube/assets/36297463/0c97daac-f4b4-4fbd-8c7c-b57d834aec84)

![image](https://github.com/7x11x13/songs-to-youtube/assets/36297463/e7902ef9-6f4c-4f16-a821-bbb914767a29)

**Comment by 7x11x13** [comment]
If you upload to YouTube, is it still blank? The videos are optimized to take the least time to create while still being able to be processed by YouTube, they may not be viewable in all video players.

**Comment by iansquenet** [comment]
It takes forever for YouTube to process and pretty much gets stuck in process.

**Comment by 7x11x13** [comment]
What version of ffmpeg do you have?

**Comment by iansquenet** [comment]
version 2024-04-18-git-35ae44c615-full_build-www.gyan.dev

**Comment by 7x11x13** [comment]
Can you try with ffmpeg version 6.1.1 instead? Also, could you send me some of the videos it outputs?

**Comment by iansquenet** [comment]
Oddly enough uploading works fine now.
