### ISSUE TITLE
feature request: customizable timestamps

### ISSUE THREAD

**Issue by hujiba** [7x11x13/songs-to-youtube#8]
This program is great, and has almost all the customization that I could ever want, but I don't like that the artist name is included in the timestamps in album uploads. I'd like to have some customizability of the timestamps so I can make them only have the track title, along with getting rid of the hour digit, as shown here
![firefox_kuJZwGUuga](https://user-images.githubusercontent.com/34780215/123013806-c3897080-d379-11eb-89c8-6a0344b8c3f9.png)

**Comment by 7x11x13** [comment]
The timestamps are actually based on the video titles of the songs if they were uploaded individually so you can change those values there. I implemented more customizable timestamps anyways though (as a global option), I was pretty lazy about the time formatting so I might redo that later but whatever.
