### ISSUE TITLE
Playlists not showing up when uploading video

### ISSUE THREAD

**Issue by hujiba** [7x11x13/songs-to-youtube#9]
When uploading a song, everything works perfectly fine until it tries to add to a playlist. It uploads the video and creates a new playlist with the right name, but when it tries to choose that playlist to add to it isn't there. None of the playlists are there, in fact. This is the screenshot it provides:
![image](https://user-images.githubusercontent.com/34780215/123155506-0cdecc00-d41d-11eb-9523-3a7d2e215661.png)
There should be a bunch of playlists there but it says none are available. The error in the console is:
```[12:15:39] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 119, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 146, in upload
  File "youtube_uploader_selenium\__init__.py", line 316, in __upload
Exception: Could not find playlist: MartiniEldritch - CATALYST GUY!```
I'm pretty sure this is on YouTube's end so I'm not sure if it's possible to fix.

Edit: I should add that this only started happening recently and I uploaded a bunch more videos without a problem.

**Comment by 7x11x13** [comment]
Looks like there's an error underneath the playlist window, what happens when you try to upload a video normally?

**Comment by hujiba** [comment]
It says that the daily upload limit was reached, which seems to be the same error as is under the playlist window.

**Comment by 7x11x13** [comment]
Closing this since I don't think it's related to the app, but if you encounter the same problem and the problem doesn't occur when you upload normally I'll reopen this
